// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCKFU5nBeF9N9rOP8kY6_va0YTp3WUzgs',
    appId: '1:11033230405:web:b058acfc2da16781cf372c',
    messagingSenderId: '11033230405',
    projectId: 'school-diary-f0d1b',
    authDomain: 'school-diary-f0d1b.firebaseapp.com',
    storageBucket: 'school-diary-f0d1b.appspot.com',
    measurementId: 'G-F8MFVSH4CL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSX8C2tPwUCuQRiyGlKFdgEkDheaSF56o',
    appId: '1:11033230405:android:711938c182490285cf372c',
    messagingSenderId: '11033230405',
    projectId: 'school-diary-f0d1b',
    storageBucket: 'school-diary-f0d1b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrD4B6EBH3wU30nT5Bk5N2BlB0CCA0al0',
    appId: '1:11033230405:ios:60eee77432681829cf372c',
    messagingSenderId: '11033230405',
    projectId: 'school-diary-f0d1b',
    storageBucket: 'school-diary-f0d1b.appspot.com',
    iosClientId: '11033230405-f1g4uv1mhs3kq4o4a1a64g2an7vlr14s.apps.googleusercontent.com',
    iosBundleId: 'com.widgetshubs.schoolDiary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrD4B6EBH3wU30nT5Bk5N2BlB0CCA0al0',
    appId: '1:11033230405:ios:60eee77432681829cf372c',
    messagingSenderId: '11033230405',
    projectId: 'school-diary-f0d1b',
    storageBucket: 'school-diary-f0d1b.appspot.com',
    iosClientId: '11033230405-f1g4uv1mhs3kq4o4a1a64g2an7vlr14s.apps.googleusercontent.com',
    iosBundleId: 'com.widgetshubs.schoolDiary',
  );
}
